### PR TITLE
Create a root_VS2015 corresponding to the Visual Studio 2015.

### PR DESCRIPTION
**Pull request by daisukenishino**
https://github.com/OpenTouryoProject/OpenTouryo/issues/113

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
There are two problems.
- In the machine which only Visual Studio 2015 has been installed in, the build using MSBuild fails.
    - "...\Microsoft\VisualStudio\v11.0\WebApplications\Microsoft.WebApplication.targets" does not exist.
    - e.g. MVC_Sample
- The build for the projects using PortableClassLibrary fails.
    - None of batch files run the build for PortableClassLibrary.sln.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

### The build using MSBuild failed.  
I think this is environmental issues.  
Is there possibility to resolved by modifying the contents of the repository ?

### The build of PortableClassLibrary(PCL)
I had register matter of batch files to the "issue".
- Improvement of the build system - Issue #119 - OpenTouryoProject-OpenTouryo
https://github.com/OpenTouryoProject/OpenTouryo/issues/119

There are two possibilities about the failure of PCL's build.
- There is a problem with the version of TargetFramework of PCL.
- Since PCL can not build the Express edition of VS, I stored it to the repository.  
But, there is a possibilities that was deleted by execute the 1_DeleteDir.bat or 2_DeleteFile.bat.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

- We will investigate for "The build using MSBuild failed".
- We will conduct the correspondence of [Issue119](https://github.com/OpenTouryoProject/OpenTouryo/issues/119) partially for "The build of PortableClassLibrary(PCL)".
  - "Correspondence to MSbuild"  
MSBuild will be used as default tool by this changes.
  - "Build of PortableClassLibrary"  
Add the Build.bat file of PortableClassLibrary to appropriate location.

Is there no problem with this  correspondence ?

**Comment by yusukemaegawa** [comment]
@daisukenishino 
Yes, please keep going with the work the way you are.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Please see the https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/18#issuecomment-151017667

- Please investigate the measures of above problem "The build using MSBuild failed".
- Please implement the following two corresponding in "Issue#119" to root_VS2015 folder.
  - "Correspondence to MSbuild"  
MSBuild will be used as default tool by this changes.
  - "Build of PortableClassLibrary"  
Add the Build.bat file of PortableClassLibrary to appropriate location.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We will investigate about "The build using MSBuild failed".
We will also discuss about this issue in the meeting, for better understanding.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Currently, this work has the highest priority.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Implementation of batch file is done.
We are not getting any MSBuild error, it is working fine in our environment.
But, we want to test in your environment.
As in the below comment, we have requested to share the environment for testing.
https://github.com/OpenTouryoProject/OpenTouryo/issues/119#issuecomment-152505385

or
If this testing is done by you, 
Then, Shall we commit the batch file?

Please let us know.

**Comment by daisukenishino** [comment]
@SandeepNayak077 
I wanted to confirm today, but it is going to be November 4.
In addition, investigation of problems in VS2013 is out of scope.

@yusukemaegawa 
We need information about the environment that caused [this problem](https://github.com/OpenTouryoProject/OpenTouryo/issues/119#issuecomment-152463361).
This is because, the problem does not reproduce in the @SandeepNayak077's environment.

**Pull request closed without merging**
