### PR TITLE
Fixed : "The debug of website e.g. : "ProjectX_sample" in "root_VS2013" fails." #12

### LINKED ISSUE #12: The debug of website e.g. : "ProjectX_sample" in "root_VS2013" fails.
Until Visual Studio 2012, I could set the value of virtual path.
Therefore, the url of page includes the value of virtual path.

>e.g.
>http://localhost:9999/ProjectX_sample/Aspx/start/menu.aspx

But, in Visual Studio 2013, I cannot set the value of virtual path.
Therefore, the url of page does not include the value of virtual path.

>e.g.
>http://localhost:9999/Aspx/start/menu.aspx

In some code, the urls including the value of virtual path are still remaining.
Because of this reason, the debug of "ProjectX_sample" fails.

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #12

##### CSharp
- Except WSClientWinStore_sample.  
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/73
- WSClientWinStore_sample and ProjectX_sample.  
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/107

##### VB
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/110

##### TMProtocolDefinition2
- Introduced a new file TMProtocolDefinition2 to resolve the URL issue.  
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/108
- Removed port number of web service URL in the TMProtocolDefinition file.  
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/113

##### CSharp
- Except WSClientWinStore_sample.  
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/111
- WSClientWinStore_sample and ProjectX_sample.  
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/114

##### VB
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/112

##### FxXMLTMProtocolDefinition 
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/116
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/119

##### Else
- Modification of Readme.md.  
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/118

### CODE REVIEW

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I acquired a diff of root_VS2013 and root_VS2012 in the nisino branch.
I think that the merge work has been completed correctly.

However, the following questions of before merge has occurred by comparing the develop branch and nisino branch.

- Please change "FxXMLTMProtocolDefinition" of appsettings to "TMProtocolDefinition2.xml" as default  at VS2013 or later version  (Default setting does not include the project name in the URL).
- I think that SCDefinition2.xml is also needed like "TMProtocolDefinition2.xml" at VS2013 or later version.
- Test of the changed place is performed enough ?

Please tell us your opinion.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>- Test of the changed place is performed enough ?

Do you think the test in this time is not good enough?
If so, please point out the insufficiencies to @SandeepNayak077.

**Comment by daisukenishino** [comment]
@yusukemaegawa 
@SandeepNayak077 

>Do you think the test in this time is not good enough?

I had not found that the test is insufficient.
We have only performed test of simple confirmation
 that it through the normal case coverage of code.

But, We have not been performed detail test.
And, I do not know the test case that has been digested with this fix.

Therefore, I want to be explaned about digested test case by @SandeepNayak077.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>- I think that SCDefinition2.xml is also needed like "TMProtocolDefinition2.xml" at VS2013 or later version.

What is the purpose of creating SCDefinition2.xml?
In the latest SCDefinition.xml, the urls do not include the name of virtual directory.
And, this file is usable in both IIS and IISExpress.
```xml
	<Screen value="~/Aspx/start/login.aspx" directLink="allow">
		<Transition value="~/Aspx/start/menu.aspx" label="menu"/>
	</Screen>
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 
@SandeepNayak077 

>And, this file is usable in both IIS and IISExpress.

I see. You're right.
"SCDefinition2.xml" correspondence is not required.

**Comment by SandeepNayak077** [comment]
@daisukenishino 
@yusukemaegawa 

Sorry for the late response due to internal work.

> Test of the changed place is performed enough ?

Test is performed about this activity and shared the evidences in IPS.

> I think that SCDefinition2.xml is also needed like "TMProtocolDefinition2.xml" at VS2013 or later version.

It is not required to create <b>SCDefinition2.xml</b>,
Because the URLs in this will be internally resolved by the framework ([here](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Frameworks/Infrastructure/Framework/Presentation/BaseController.cs#L3720)).

Our only concern is the files which are present in [this location](https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino/root_VS2013/files/resource/Test/scd) are need to be modified.
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Test is performed about this activity and shared the evidences in IPS.

Please let me know the location by e-mail.

>Our only concern is the files which are present in this location are need to be modified.

I see.
There is no need to correspond this.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

> https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/116#issuecomment-195230299

Please cope with the above comment.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Please describe develop/run-time environment in readme in root folder.

e.g.
# Open棟梁(OpenTouryo)

"Open棟梁" は、長年の.NETアプリケーション開発実績にて蓄積したノウハウに基づき開発した.NET Framework用アプリケーション フレームワークです。
("OpenTouryo" is an application framework for .NET Framework which was developed using the accumulated know-how with a long track record in .NET application development.)

テンプレート・ベースに同梱されるサンプルはOpen棟梁の評価に利用できます。
また、テンプレート・ベースをチュートリアルの内容に従いカスタマイズすることで
当該Visual Studioバージョンの案件向けプロジェクト・テンプレートを作成できます。 
(You can see what OpenTouryo is according to template-base.
Further, you can create the "project template" using proper version of Visual Studio.
Tutorial will be helpful to you for customizing template-base!)

詳しくは、各フォルダのReadmeをご参照ください。
(For more information, please refer to the Readme in each root_VS20XX folder.)

## 内容物(contents)

### [/license/](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/license)
ライセンス(license)

### テンプレート・ベース（Template-base）

|Template-base|Develop Environment|Run-time Environment|
|:-----|:------------------|:-------------------|
|[/root_VS2010/](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2010)|Visual Studio 2010|.NET Framework 3.5 SP1|
|[/root_VS2012/](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2012)|Visual Studio 2012|.NET Framework 4.5|
|[/root_VS2013/](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2013)|Visual Studio 2013|.NET Framework 4.5.1|
|[/root_VS2015/](https://github.com/OpenTouryoProject/OpenTouryoTemplates/tree/master/root_VS2015)|Visual Studio 2015|.NET Framework 4.6|

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Now, this have all fixes by the our efforts.
Please merge this ASAP.

**Pull request merged**
