### PR TITLE
Fixed : "The NuGet correspondence in the task of improvement of the build system."

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed https://github.com/OpenTouryoProject/OpenTouryo/issues/119

- [Investigated and removed unused DLLs from the MVC_Sample and SPA_Sample projects #82](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/82)
- [Did NuGet correspondence in the frameworks of root_vs2015 #90](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/90)
- [Included the current latest version of NuGet.exe file #97](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/97)
- [Did the following modification to accomplish NuGet correspondence for the MVC and SPA #98](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/98)
- [Did NuGet correspondence for WinStore sample #99](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/99)
- [Modified the followings to accomplish the NuGet correspondence. #100](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/100)

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Two "packages" folders remain [here](https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino/root_VS2015/programs/C%23/Samples/WinAzure_sample/packages) and [here](https://github.com/SymphonyTeleca/OpenTouryoTemplates/tree/nishino/root_VS2015/programs/C%23/Samples/WS_sample/WSClient_sample/WSClientWinStore_samples/packages).

Certainly, [Issue #119](https://github.com/OpenTouryoProject/OpenTouryo/issues/119) does not describe WinAzure_sample.sln and WSClientWinStore_sample.sln.
Why didn't you include these two solutions in target solutions of [Issue #119](https://github.com/OpenTouryoProject/OpenTouryo/issues/119)?

I think that you should delete these two "packages" folders.
If these two "packages" remain, I think that "NuGet correspondence" has not been yet completed.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

Correspondance of the WinAzure_sample and WSClientWinStore_sample was not included in this request. At a later date I will correspond this. Please merge this pull request.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

The "[pr #100](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/100)" was merged.
Please merge because all of preparation has been completed.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I confirmed the following things.
- There are not "packages" folders in root_VS2015 folder.
- Whether I build using MSBuild or devenv.com, all nuget packages can be downloaded automatically.
- Whether I build using MSBuild or devenv.com, all batch files can be executed successfully.

I think that you can also perform this "Nuget correspondence" for root_VS2012 and root_VS2013.
Do you have any plans for performing this "Nuget correspondence" for root_VS2012 and root_VS2013?

Please tell me your opinion.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>I think that you can also perform this "Nuget correspondence" for root_VS2012 and root_VS2013.
Do you have any plans for performing this "Nuget correspondence" for root_VS2012 and root_VS2013?

>Please tell me your opinion.

Since Nuget support status may be different according to version, 
the target of Nuget correspondnce is focused on only root_VS2015.

see : https://github.com/OpenTouryoProject/OpenTouryo/issues/119

**Comment by yusukemaegawa** [comment]
@daisukenishino 

I already know that [Issue #119](https://github.com/OpenTouryoProject/OpenTouryo/issues/119) describe only root_VS2015.

But, the sizes of root_VS2012 and root_VS2013 are also too large because of "packages" folders.
So, I want you to correspond for root_VS2012 and root_VS2013.
(I think that the way of MSBuild Integration does not vary between versions of Visual Studio.)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

It was registered with [the issue](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/37).
Please merge this pullrequest.

**Pull request merged**
