### PR TITLE
Fixed : "To merge the changes ( - Until September 30)." #185

### PR DESCRIPTION
**Pull request by daisukenishino**
# Fixes
Fixed https://github.com/OpenTouryoProject/OpenTouryo/issues/182
- [Fixed : "Reflect the latest update of common.js to the MVC version." #182](https://github.com/OpenTouryoProject/OpenTouryo/issues/182)

Fixed https://github.com/OpenTouryoProject/OpenTouryo/issues/185
- [Fixed : "To merge the changes ( - Until September 30)." #185](https://github.com/OpenTouryoProject/OpenTouryo/issues/185)

# pull-requests
- [Merged the code changes from root to root_VS2010 for C# version. #169](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/169)
- [Merged the code changes from root_VS2012 to root_VS2013 for C# version. #172](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/172)
- [Merged the code changes from root_2010 to root_VS2012 for C# version. #171](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/171)
- [Merged the following from root_VS2013 to root_VS2015 for C# version. #173](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/173)
- [Merged the code changes from root to root_2010 for VB version. #174](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/174)
- [Merged the code changes from root_VS2010 to root_VS2012 for VB version. #175](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/175)
- [Merged the following from root_VS2012 to root_VS2013 for VB version. #176](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/176)
- [Merged the following from root_VS2013 to root_VS2015 for VB version. #177](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/177)
- [Modified the following to complete merge work #178](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/178)
  - Corrected comment header in C# and added comment header in VB for root_VS2010-root_VS2015
  - Merged WinStore_sample from root_VS2012 to root_VS2013 and root_VS2013 to root_VS2015
  - Added missing dll of PCL to root_VS2010
- [Modified Comment history in OpenTouryoTemplates for C# and VB version as per review comment.
#179](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/179)

### Fixes of found problems
- [Fixed the issue identified in Global.asax and App_Code for both C# and VB #180](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/180)
- [Fixed Json service changes #181](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/181)

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

When running *3_Build_PortableClassLibrary.bat* in *root_VS2015\programs\C#* folder, the following error occurs:
```txt
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(283,22): error MSB4086: 条件 "'$(TargetPlatformVersion)'>= '10.0.11000.0'" で、数字ではなく "10.0.11000.0" と評価された "10.0.11000.0" に対して、数値比較を実行しようとしました。 [C:\Users\y-maegawa\Desktop\OpenTouryoTemplates-nishino\root_VS2015\programs\C#\Frameworks\PortableClassLibrary\PCLFramework\PCLFramework.csproj]
```

This error is eliminated by running the following command referring to [this site](http://stackoverflow.com/questions/38181160/error-running-msbuild).
```bat
call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"
```

Please confirm.

Note:
Because *C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat* does not exist on my computer, I used *C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat*.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I see.
I am checking it now.

@SandeepNayak077 

I detected a very rudimentary problem.
Please correspond as soon as possible.

image

This maybe occurred in the code separation of Global.asax.

**Comment by yusukemaegawa** [comment]
@svkumar2810 
@SandeepNayak077 
@daisukenishino 

[Global.asax.cs](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/1d582dfd398c2f84c946810becbeda8af5701167/root_VS2012/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Global.asax.cs) is implemented as follows:
```cs
namespace ProjectX_sample
{
    /// <summary>Global.asax class </summary>
    public class Global : System.Web.HttpApplication
    {
        (the rest omitted)
    }
}
```

Therefore, I think that class name is *ProjectX_sample.Global*, not *ProjectX_sample.Global_asax*.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I checked that it works by modifying as follows.

https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/1d582dfd398c2f84c946810becbeda8af5701167/root_VS2012/programs/C%23/Samples/WebApp_sample/ProjectX_sample/Global.asax
```CS
<%@ Application Codebehind="Global.asax.cs" Inherits="ProjectX_sample.Global_asax" Language="C#" %>
```
▼ ▼ ▼
```CS
<%@ Application Codebehind="Global.asax.cs" Inherits="ProjectX_sample.Global" Language="C#" %>
```

@svkumar2810 
@SandeepNayak077 

Please correspond as soon as possible.

**Comment by svkumar2810** [comment]
@daisukenishino ,

Sure, we will modify it accordingly and send you the pull request.

**Comment by svkumar2810** [comment]
@daisukenishino 

We have found another problem with Global.asax.cs. In web application in C# either we can keep Global.aspx.cs or App_Code to make the application work. 
As of now we have both **Global.asax.cs** and **App_Code** folder in **Project X_Sample**. Can we rename **App_Code** to **AppCode** or alternatively we can keep only **Global.asax** and delete  **Global.asax.cs** and send you the pull request. 

The problem has caused after splitting Global.asax and Global.asax.cs files.

Please confirm, so that we can proceed further. Sorry for the inconvenience.

**Comment by daisukenishino** [comment]
@svkumar2810 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/57#issuecomment-250415595

Do you insist that both of **Global.aspx.cs** and **App_Code** folder can't exist in the "**web application project**" ?

I believe that there is no such constraint as above by my experience.
if not so, please provide the source of information of the constraint.

**Comment by svkumar2810** [comment]
@daisukenishino 

> Do you insist that both of Global.aspx.cs and App_Code folder can't exist in the "web application project" ?

Not exactly. But the issue is only when we add Global.aspx.cs. With only Global.aspx file as it existed previously, there was no such issue, we even tested it. 
Now, If I rename the App_Code to AppCode it works fine. So this made to me to conclude as above.
Please suggest

**Comment by daisukenishino** [comment]
@svkumar2810 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/57#issuecomment-250428009
Please suggest.

I checked that the matter of **App_Code** folder is another issue.

- 【ASP.NET】App_Codeフォルダに配置したクラスが参照できない。 - ものぐさ日記（仮）  
http://monogusa.hatenablog.com/entry/2013/03/04/223617

When add a class to the **App_Code** folder, there is a need to change the build action to be "**compile**", because this default is "**content**". For this reason, it is better that don't place "**App_Code**" folder in "**web application project**".

**Comment by svkumar2810** [comment]
@daisukenishino 

>For this reason, it is better that don't place "App_Code" folder in "web application project".
Add your review

So, can we correspond by renaming the App_Code folder to AppCode and send you the pull request. Please confirm.

**Comment by daisukenishino** [comment]
@svkumar2810 

TODO is the following two items.
- Change the class name of inherits in **Global.asax**  
as "**ProjectX_sample.Global**" from "**ProjectX_sample.Global_asax**".
- Rename the **App_Code** folder's name to be "**AppCode**".

**Comment by svkumar2810** [comment]
@daisukenishino 

I confirm that we will be working on following two items,

> - Change the class name of inherits in Global.asax
as "ProjectX_sample.Global" from "ProjectX_sample.Global_asax".
> - Rename the App_Code folder's name to be "AppCode".

**Comment by daisukenishino** [comment]
@yusukemaegawa 

There is a problem in the following.
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/181

But please merge once in order to do fix tasks at this repository, hereafter.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>There is a problem in the following.
>https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/181

It seems that *CodeBehind* property is *optional* in svc file. (Refer [MSDN](https://msdn.microsoft.com/en-us/library/aa967286(v=vs.110).aspx) and [stackoverflow](http://stackoverflow.com/questions/7318702/wcf-servicehost-codebehind).)
Therefore, wcf service *JSONService.svc* works normally.

**Pull request merged**
