### PR TITLE
Fixed : "To merge the changes ( - Until March 31)" #131

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed https://github.com/OpenTouryoProject/OpenTouryo/issues/131

All of Diff checks and Build checks had been completed.
Please merge the current pullrequest after the review has been completed.

##### VS2010
- [Merged from root to root_VS2010 for C# version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/124)
- [Merged from root to root_VS2010 for VB version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/128)

##### VS2012
- [Merged from root_2010 to root_2012 for C# version ](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/134)
- [Merged from root_2010 to root_2012 for VB version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/133)

##### VS2013
- [Merged from root_2012 to root_2013 for C# version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/136)
- [Merged from root_2012 to root_2013 for VB version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/135)

##### VS2015
- [Merged from root_2013 to root_2015 for C# version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/138)
- [Merged from root_2013 to root_2015 for VB version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/137)

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

In **Japanese** Windows OS, the literal of DaoGen_Tool is **not** displayed in Japanese.
(The literal is displayed in **English**.)

Target Version: root_VS2010
(The above may occur in other version.)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-205638577

I can't found this issue on my develop environment.
Please tell me your develop environment.
image

**Comment by daisukenishino** [comment]
@yusukemaegawa 

All of Diff checks and Build checks had been completed.
Please merge the current pullrequest after the review has been completed.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

OS : Windows 7 Professional SP1
Visual Studio : 2012 - 2015

I executed all build batch files and run DaoGen_Tool.exe.
And, the literal is displayed in English.
daogen_tool

**Comment by daisukenishino** [comment]
@yusukemaegawa 

There is a possibility that there is a problem in the environment settings for the culture of .NET.

I've updated the related issue comment.
https://github.com/OpenTouryoProject/OpenTouryo/issues/167

Please try to change the DefaultCulture.
https://github.com/OpenTouryoProject/OpenTouryo/blob/develop/root/programs/C%23/Frameworks/Tools/DPQuery_Tool/app.config#L211
- en
- ja
- ja-jp
- delete this setting

##### 余談
間違っている。
- 棟梁 ≠ master builder
- 棟梁 = touryo

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>[OpenTouryo/Issues/108](https://github.com/OpenTouryoProject/OpenTouryo/issues/108)

The words "Indispensabile" still remain.
-https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Aspx/testFxLayerP/wcc/testWCTextBox.aspx#L21
-https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Aspx/testFxLayerP/wcc/testWCTextBox.aspx#L145
-https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Aspx/testFxLayerP/wcc/testWCTextBox.aspx#L21
-https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Aspx/testFxLayerP/wcc/testWCTextBox.aspx#L145

**Comment by daisukenishino** [comment]
@SandeepNayak077

As soon as possible, please send a Pullrequest after correspond [above correspondence](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-205718090).

**Comment by daisukenishino** [comment]
@yusukemaegawa 

It has been fixed.
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/141/files

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>[OpenTouryo/Issues/145](https://github.com/OpenTouryoProject/OpenTouryo/issues/145)

The words "WSClientSL_sample.Web" still remain.
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/AppCode/sample/Business/LayerB_mu.cs#L54
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/AppCode/sample/Business/LayerB_rt.cs#L56

And more...

**Comment by daisukenishino** [comment]
@SandeepNayak077 

##### root_VS2013
Delete following.
These are modules associated with general-purpose service interface toward Silverlight .
```
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\Authentication.cs(52,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\Authentication.cs(56,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_mu.cs(52,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_mu.cs(54,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_rt.cs(54,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_rt.cs(56,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_sb.cs(52,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_sb.cs(54,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2013\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Dao\LayerD_mu.cs(52,19)  [UTF-8]: namespace WSClientSL_sample.Web.Dao
```

Please remove partially the definition related to the above.
```
...\root_VS2013\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(12,75)  [UTF-8]:  	<Transmission id="muWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_mu" />
...\root_VS2013\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(13,75)  [UTF-8]:  	<Transmission id="sbWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_sb" />
...\root_VS2013\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(14,75)  [UTF-8]:  	<Transmission id="rtWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_rt" />
...\root_VS2013\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(16,77)  [UTF-8]:  	<Transmission id="Authentication" assemblyName="dummy" className="WSClientSL_sample.Web.Business.Authentication" />
```

##### root_VS2015
Same as above.
```
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\Authentication.cs(52,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\Authentication.cs(56,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_mu.cs(52,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_mu.cs(54,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_rt.cs(54,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_rt.cs(56,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_sb.cs(52,15)  [UTF-8]: using WSClientSL_sample.Web.Dao;
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Business\LayerB_sb.cs(54,19)  [UTF-8]: namespace WSClientSL_sample.Web.Business
...\root_VS2015\programs\C#\Samples\WinAzure_sample\ProjectX_sample\AppCode\sample\Dao\LayerD_mu.cs(52,19)  [UTF-8]: namespace WSClientSL_sample.Web.Dao
```

```
...\root_VS2015\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(12,75)  [UTF-8]:  	<Transmission id="muWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_mu" />
...\root_VS2015\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(13,75)  [UTF-8]:  	<Transmission id="sbWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_sb" />
...\root_VS2015\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(14,75)  [UTF-8]:  	<Transmission id="rtWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_rt" />
...\root_VS2015\programs\C#\Samples\WinAzure_sample\resource\Xml\TMInProcessDefinition.xml(16,77)  [UTF-8]:  	<Transmission id="Authentication" assemblyName="dummy" className="WSClientSL_sample.Web.Business.Authentication" />
```

**Comment by daisukenishino** [comment]
@SandeepNayak077 

##### Additional request
I want to merge the changes of **"\WebApp_sample\ProjectX_sample\"** of ver 01-72 to **"\WinAzure_sample\ProjectX_sample\"**. In addition, [modification of the unstable state](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36) is not required.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

As we have discussed in the call,
We will first remove the code as mentioned in [this above comment](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-206126700).
Merge required code or files from "\WebApp_sample\ProjectX_sample\" to "\WinAzure_sample\ProjectX_sample\".

After the merge,
 If possible, we will check to resolve the [unstable state](https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36) issue and commit with fix.
Otherwise we will commit only the merged code of ProjectX_sample.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-206318642

Please do so.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for the confirmation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

<h3>Merge Difference</h3>

<b>(1) CodeFile vs Codebehind:</b>

In @ Page directive, there is difference of CodeFile(\WebApp_sample\ProjectX_sample\) and Codebehind (\WinAzure_sample\ProjectX_sample\) in all *.aspx files.

Does it required to merge?

<b>(2) URL and IE 11 issue related difference:</b>

In all *.aspx, *.aspx.cs and DialogFrame.htm, there are differences of URL issue and IE11 issue. 
We think this is required to merge.
Please confirm.

<b>(3) Web.config:</b>

app.config settings are written in the web.config file.
Does it required to create app.config file?

Does it required to merge Webservice and JQGridJson related setting?
Please confirm.

<b>(4) Other differences</b>

- Textbox Textchanged event: \ProjectX_sample\Aspx\testFxLayerP\normal\testScreen2.* <b>(Required to merge)</b>.
- Event handler to the user control: \ProjectX_sample\Aspx\sample\crud\sampleScreen.* <b>(Required to merge)</b>.
- 3Tier screens: <b>(Required to merge)</b>.
 - ProductsConditionalSearch.*
 - ProductsDetail.*
 - ProductsSearchAndUpdate.* 
- Keboard events: \ProjectX_sample\Framework\Js\ie_key_event.js <b>(Not required to merge)</b>.
- Application events: \ProjectX_sample\Global.asax <b>(Not required to merge)</b>.

please confirm.

<b>(5) JQGrid and JSON related files</b>
- \ProjectX_sample\WebService
- \ProjectX_sample\Scripts
- \ProjectX_sample\Content
- \ProjectX_sample\Aspx\testFxLayerP\table\testListView.*
- \ProjectX_sample\Aspx\testFxLayerP\table\testJQGridJson.*

We think these files not required to merge.
Please confirm.

<b>Note:</b>
We have already started merging (2) and (4) [having Requred to merge].

**Comment by SandeepNayak077** [comment]
@daisukenishino 

We have updated the (4) point in the above comment and created [pull request-144](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/144).

**Comment by daisukenishino** [comment]
@SandeepNayak077 

##### (1) CodeFile vs Codebehind:
You do not need to merge this difference.
Azure PaaS should be a Web application rather than a Web site.
Therefore, Azure PaaS of * .aspx.cs is required to be Codebehind.

##### (2) URL and IE 11 issue related difference:
Yes. There is a need to merge the difference.

##### (3) Web.config:
You do not need to merge this difference.

In Azure PaaS the appSettings could not be separated in another file.
In addition, the difference of about JQGrid and the Webservice are not required merge.

##### (4) Other differences
This time, this merge is not required.
However, please send the Report output of WinMerge.

##### (5) JQGrid and JSON related files
You do not need to merge this difference.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

In this time, this was urgent correspondence.
Fixes of the above of (4) and (5) and the part of the (3),
there is a possibility to ask these correspondence in https://github.com/OpenTouryoProject/OpenTouryoTemplates/issues/36.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>[OpenTouryo/Issues/145](https://github.com/OpenTouryoProject/OpenTouryo/issues/145)

The path of WinStore_sample.sln that described in Readme.md is incorrect.
```md
- Windowsストアアプリ の場合(In the case of Windows Store App )：  
C:\root\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWinStore_samples\WSClientWinStore_samples.sln
```

- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2012/Readme.md
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/Readme.md
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/Readme.md

**Comment by daisukenishino** [comment]
@yusukemaegawa 

This was modified as the follows.
```TXT
C:\root\programs\C#\Samples\WS_sample\WSClient_sample\WSClientWinStore_samples\WSClientWinStore_samples.sln
```
▼ ▼ ▼
```TXT
C:\root\programs\C#\Samples\WinStore_samples\WinStore_samples.sln
```

Please check the modification.
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2012/Readme.md
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/Readme.md
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/Readme.md

**Comment by yusukemaegawa** [comment]
@daisukenishino 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-207192823

I have checked Readme.md.
OK.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

[WebApp_sample/ProjectX_sample/app.config](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Samples/WebApp_sample/ProjectX_sample/app.config)
```xml
  <add key="FxErrorScreenPath" value="~/Aspx/Common/ErrorScreen.aspx"/>
  <add key="FxOKMessageDialogPath" value="~/Aspx/FrameWork/myOKMessageDialog.aspx"/>
  <add key="FxYesNoMessageDialogPath" value="~/Aspx/FrameWork/myYesNoMessageDialog.aspx"/>
  <add key="FxDialogFramePath" value="~/Aspx/Framework/DialogFrame.htm"/>
  <!-- アイコンパス -->
  <add key="FxInformationIconPath" value="~/Framework/img/information.ico"/>
  <add key="FxWarningIconPath" value="~/Framework/img/warning.ico"/>
  <add key="FxErrorIconPath" value="~/Framework/img/error.ico"/>
  <add key="FxQuestionIconPath" value="~/Framework/img/question.ico"/>
```

---> Each paths start with "~".

[WinAzure_sample/ProjectX_sample/Web.config](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Web.config)
```xml
    <!-- 基盤画面パス -->
    <add key="FxErrorScreenPath" value="/Aspx/Common/ErrorScreen.aspx"/>
    <add key="FxOKMessageDialogPath" value="/Aspx/FrameWork/myOKMessageDialog.aspx"/>
    <add key="FxYesNoMessageDialogPath" value="/Aspx/FrameWork/myYesNoMessageDialog.aspx"/>
    <add key="FxDialogFramePath" value="/Aspx/Framework/DialogFrame.htm"/>
    <!-- アイコンパス -->
    <add key="FxInformationIconPath" value="/Framework/img/information.ico"/>
    <add key="FxWarningIconPath" value="/Framework/img/warning.ico"/>
    <add key="FxErrorIconPath" value="/Framework/img/error.ico"/>
    <add key="FxQuestionIconPath" value="/Framework/img/question.ico"/>
```

---> Each paths **do not** start with "~".

Is "~" unnecessary?

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Please answer for [the above](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-207202316).

**Comment by daisukenishino** [comment]
@yusukemaegawa 

[This](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-207202316) was modified as the follows.
```xml
  <!-- 基盤画面パス -->
  <add key="FxErrorScreenPath" value="~/Aspx/Common/ErrorScreen.aspx"/>
  <add key="FxOKMessageDialogPath" value="~/Aspx/FrameWork/myOKMessageDialog.aspx"/>
  <add key="FxYesNoMessageDialogPath" value="~/Aspx/FrameWork/myYesNoMessageDialog.aspx"/>
  <add key="FxDialogFramePath" value="~/Aspx/Framework/DialogFrame.htm"/>
  <!-- アイコンパス -->
  <add key="FxInformationIconPath" value="~/Framework/img/information.ico"/>
  <add key="FxWarningIconPath" value="~/Framework/img/warning.ico"/>
  <add key="FxErrorIconPath" value="~/Framework/img/error.ico"/>
  <add key="FxQuestionIconPath" value="~/Framework/img/question.ico"/>
```
▼ ▼ ▼
```xml
    <!-- 基盤画面パス -->
    <add key="FxErrorScreenPath" value="/Aspx/Common/ErrorScreen.aspx"/>
    <add key="FxOKMessageDialogPath" value="/Aspx/FrameWork/myOKMessageDialog.aspx"/>
    <add key="FxYesNoMessageDialogPath" value="/Aspx/FrameWork/myYesNoMessageDialog.aspx"/>
    <add key="FxDialogFramePath" value="/Aspx/Framework/DialogFrame.htm"/>
    <!-- アイコンパス -->
    <add key="FxInformationIconPath" value="/Framework/img/information.ico"/>
    <add key="FxWarningIconPath" value="/Framework/img/warning.ico"/>
    <add key="FxErrorIconPath" value="/Framework/img/error.ico"/>
    <add key="FxQuestionIconPath" value="/Framework/img/question.ico"/>
```

Please check the modification.
- https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Web.config

**Comment by daisukenishino** [comment]
@SandeepNayak077 

It was confirmed that the **unstable state** is resolved.
Correspondence of matter of the **"~"** was not required for AzurePaaS.
However, we have merged for consistency with the other.

Work of the merge was complete.
Thank you for your cooperation.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Thank you for your support.
There was holiday on 08-Apr-2016, so we could not reply your queries.

> https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/44#issuecomment-207148844
> (4) Other differences
> However, please send the Report output of WinMerge.

Shall we create report out?
Or
Shall we work with [issue#169](https://github.com/OpenTouryoProject/OpenTouryo/issues/169)?
Please let us know the priority of work.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

Please preceded the high-priority task.
- [How to reflect partially the difference of IE11 correspondence of the "01-72" version on the "01-71" version ? #169](https://github.com/OpenTouryoProject/OpenTouryo/issues/169)
- [Cross-browser-compatible correspondence of the double submission prevention function. #161](https://github.com/OpenTouryoProject/OpenTouryo/issues/161)

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Ok, we will plan accordingly.
Thank you for the confirmation.

**Pull request merged**
