### PR TITLE
Fixed : "Nuget correspondnce for root_VS2012 and root_VS2013." #37

### LINKED ISSUE #37: Nuget correspondnce for root_VS2012 and root_VS2013.
# Requirement
Remove the packages folder by nuget correspondance of sample programs.
This correspondance can significantly reduce the capacity of downloaded ZIP file.

Please check whether it is possible to correspond with VS2012 and VS2013.
Please correspondence, if it possible.

### List of the contained pullrequest 
- [Did NuGet correspondence in the frameworks of root_VS2012 #126](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126)
- [Did NuGet correspondence in the frameworks of root_VS2013 #127](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/127)
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #129](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/129)
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #130](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/130)
- [Modification of Readme.md associated with the nuget correspondence. #131](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/131)

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed #37 

### List of the contained pullrequest 
- [Did NuGet correspondence in the frameworks of root_VS2012 #126](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126)
- [Did NuGet correspondence in the frameworks of root_VS2013 #127](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/127)
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #129](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/129)
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #130](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/130)
- [Modification of Readme.md associated with the nuget correspondence. #131](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/131)

### CODE REVIEW

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I merged the following two pull requests.

- [Did NuGet correspondence in the frameworks of root_VS2012 #126](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126)
- [Did NuGet correspondence in the frameworks of root_VS2013 #127](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/127)

I will check this build process from now.
When it is completed, then I notify you.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

You do not deal with [this](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/126#issuecomment-200627963).

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I confirmed that the all problems of our "pointed out" have been resolved.

The followings areadditional pullrequests.
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #129](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/129)
- [Resolved Issues notified in Sample program SPA_Sample and MVC_Sample #130](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/130)
- [Modification of Readme.md associated with the nuget correspondence. #131](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/131)

Please merge ASAP.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

```txt
- Open 棟梁 Visual Studio 2010 テンプレート・ベースが利用するライブラリは、NuGet経由でダウンロードします。このため、プロキシ環境下でビルドバッチファイルを実行する場合、正常にライブラリがダウンロードできないことがあります。このような場合は、z_Common.bat に http_proxy 環境変数を作成し、プロキシ環境の情報を設定してください。

(OpenTouryo Visual Studio 2010 template base uses various libraries. And the libraries are downloaded by NuGet. So, NuGet might not download the libraries normally when you run the build batch files with proxy environment. In such case, create environment variable http_proxy in z_Common.bat, and set the information of proxy environment to environment variable http_proxy.)
```

I think that you do not deal with #37 to root_VS2010.

**Pull request merged**
