### PR TITLE
Fixed : "Remove a samples of the Silverlight and XBAP for to end this support." #157

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed https://github.com/OpenTouryoProject/OpenTouryo/issues/157

- [Deprecated the support of Silver light and XBAP from the root_VS2010 version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/101)
- [Deprecated the support of Silver light and XBAP from the root_VS2012 version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/102)
- [Deprecated the support of Silver light and XBAP from the root_VS2013 version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/105)
- [Deprecated the support of Silver light and XBAP from the root_VS2015 version](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/106)

The announcement is done at the time of tagging.
Thererof, please merge this.

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

In root_VS2013 and root_VS2015, there are still the links to the sample page of Silverlight.

For example:
[menu.aspx](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2015/programs/C%23/Samples/WinAzure_sample/ProjectX_sample/Aspx/start/menu.aspx#L53)
```html
    ● <a href="/WSClientSL_sampleTestPage.aspx">Silverlightサンプル</a><br />
```

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/38#issuecomment-192052374

I was corresponding to this,
but it has been delayed that it reflect to the "Files changed" tag.
Therefor, please see the above two comitts named "Update menu.aspx".

**Comment by yusukemaegawa** [comment]
@daisukenishino 

Because you deleted 11_xxx.bat, "number 11" became missing number in build batch files.
Is there any plan to do?

For example:
- Change the name of file as follows.

**12**_Build_WinStore_sample.bat -> **11**_Build_WinStore_sample.bat

**Comment by daisukenishino** [comment]
@yusukemaegawa 

At first, I thought that trying to store this [to refactoring (1)](https://github.com/OpenTouryoProject/OpenTouryo/issues/149).
But, since the merge will be difficult, I will maintain the status quo.

**Comment by yusukemaegawa** [comment]
@daisukenishino 

What is the difficult point?
I think that only changing a file name is not difficult.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I was wrong. I add this to refactoring (1).
see : https://github.com/OpenTouryoProject/OpenTouryo/issues/149#issuecomment-192104950

Please merge following pull request asap.
https://github.com/OpenTouryoProject/OpenTouryo/pull/158

**Pull request merged**
