### PR TITLE
VB migration of JQGrid ( Added required scripts and content. )

### PR DESCRIPTION
**Pull request by daisukenishino**
Added required files to displaying JQGrid.
- Added scripts folder (/ProjectX_sample/Scripts/) that includes .js files
- Added content folder (/ProjectX_sample/Content/) that includes all style sheet.

Note : This Pullrequest conduct only to add files.
　　　　Merge of the program will be conducted at the next Pullrequest.

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
I do not read "the next pull request".
I cannot make a judgement whether I should merge this pull request.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

"the next pull request" is
"VB migration of JQGrid (This sample to display the Grid to ASPX screen via WCF using jqGrid)"

Please refer to the following URL.
https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/10

**Comment by yusukemaegawa** [comment]
I am checking the pull request to OpenTouryoProject repository.
Why must I check a different repository?
Please send a pull request in conjunction with the changes of https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/10.

**Comment by yusukemaegawa** [comment]
I will perform an operation check of sample program.
Please resend the pull request that includes the sample program, CSS files, and JavaScript files.

**Comment by daisukenishino** [comment]
@yusukemaegawa 

I understood your request.
I needed the simplification of reviews by divided the pullrequest.
On the other hand, You need confirmation by actual machine.

For your actual confirmation,
I sent [one integrated pullrequest](https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/15) that was Included two pullrequest by merge the [second pullrequest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/10).

**Pull request closed without merging**
