### PR TITLE
Fixed : "Path is too long." #145

### PR DESCRIPTION
**Pull request by daisukenishino**
fixed https://github.com/OpenTouryoProject/OpenTouryo/issues/145

### CODE REVIEW

**Comment by yusukemaegawa** [comment]
@daisukenishino 

[TMInProcessDefinition.xml](https://github.com/SymphonyTeleca/OpenTouryoTemplates/blob/nishino/root_VS2013/files/resource/Xml/TMInProcessDefinition.xml) is not modified.
Please confirm.
```xml
 	<Transmission id="muWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_mu" />
 	<Transmission id="sbWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_sb" />
 	<Transmission id="rtWebService" assemblyName="dummy" className="WSClientSL_sample.Web.Business.LayerB_rt" />

 	<Transmission id="Authentication" assemblyName="dummy" className="WSClientSL_sample.Web.Business.Authentication" />
```

**Comment by daisukenishino** [comment]
@SandeepNayak077 

About https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/40#issuecomment-198147769.

Do you plan corresponding in the merge ?
I think that change of definition file should be included in this pull request.

Change of the target is the following file that WinStoreSL_sample is using.
"root_VS2012-2015/files/resource/Xml/TMInProcessDefinition.xml" file in root folder that is modified WinStoreSL_sample's path.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

> Do you plan corresponding in the merge ?

Yes we have included in the merge activity.
Because, currently other engineers are working on NuGet correspondence for WinStoreSL_sample in root_VS2012 and root_VS2013.
Once its done we will correspond this.

Or 
Shall we merge this along with the NuGet correspondence of root_VS2012?
Please confirm.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

>Please confirm.

Once its done, you should correspond this.
I don't want to correspond to this at the merge.
This is because, one pull request needs to be related to one issue.

Therefore, I want you to modify this pull request.
Please send the additional pull request after you modify the "root_VS2012-2015/files/resource/Xml/TMInProcessDefinition.xml" file by create a feature branch from nishino branch.

**Comment by SandeepNayak077** [comment]
@daisukenishino 

Okay we will as additional pull request after the NuGet correspondence.

**Comment by daisukenishino** [comment]
@SandeepNayak077 

I am waiting for additional pull request.
When this pull request merge is not completed,
I can not merge the subsequent pull requests of the following.

- [MSBuild Integration for Samples in root_2012 edition](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/121)
- [MSBuild Integration for Samples in root_VS2013 edition](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/120)

**Comment by daisukenishino** [comment]
@yusukemaegawa 

>https://github.com/OpenTouryoProject/OpenTouryoTemplates/pull/40#issuecomment-198147769

The above pointed out is modified by [the pullrequest](https://github.com/SymphonyTeleca/OpenTouryoTemplates/pull/122).
Please check and merge.

**Pull request merged**
